import './scss/_global.scss'
import Header from "./components/Header/Header";
import { rocker, montserrat, ibarra } from "@/font/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rocker.variable} ${montserrat.variable} ${ibarra.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
